### ISSUE TITLE
Using dead keys cannot let me type in `git HEAD~4`

### ISSUE THREAD

**Issue by Narigo** [fegemo/kraken-typing#1]
I have my keyboard set up with "dead keys" to make accents etc. `~` is one of them and to insert it here, I type ```SHIFT+` ``` followed by a `Space`. This prevented me to reach the next level as it never recognized the `~` in `git HEAD~4`.

**edit:** fixed formatting after over half a year :)

**Comment by fegemo** [comment]
Thanks, @Narigo! Will look into it

**Comment by fegemo** [comment]
It is now fixed.
